# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

name: "Tweet about release"
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: twwd/twitter-github-action@v1
        with:
          twitter_api_key: ${{ secrets.TWITTER_API_KEY }}
          twitter_api_secret_key: ${{ secrets.TWITTER_API_SECRET_KEY }}
          twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: |
            We just released version ${{ github.event.release.tag_name }} 🎉🎉🎉
            Thx a lot to all contributors helping us!
            Check it out here: ${{ github.event.release.html_url }}
            #release #OWASP #servicetweet
